#!/bin/sh
#
# Runs at the end of git flow hotfix start
#
# Positional arguments:
# $1    The version (including the version prefix)
# $2    The origin remote
# $3    The full branch name (including the feature prefix)
# $4    The base from which this feature is started
#
# The following variables are available as they are exported by git-flow:
#
# MASTER_BRANCH - The branch defined as Master
# DEVELOP_BRANCH - The branch defined as Develop
#
VERSION=$1
ORIGIN=$2
BRANCH=$3
BASE=$4

# Implement your script here.
merge_request=$(git push -u $ORIGIN $BRANCH -o merge_request.create -o merge_request.remove_source_branch -o merge_request.title="Draft: $BRANCH" -o merge_request.squash -o merge_request.target=$MASTER_BRANCH)
origin_url=$(git config --get remote.origin.url)
python -m webbrowser "${origin_url//.git//-/merge_requests/new?merge_request[source_branch]=$BRANCH&merge_request[target_branch]=$DEVELOP_BRANCH&merge_request[title]=Draft: $BRANCH}"

# To terminate the git-flow action, return a non-zero exit code.
exit 0
